---
- name: Update GitLab Runner config
  shell: |
    docker exec gitlab-runner sh -c "
      sed -i 's/^concurrent = .*/concurrent = {{ runner_concurrent }}/' /etc/gitlab-runner/config.toml || echo 'concurrent = {{ runner_concurrent }}' >> /etc/gitlab-runner/config.toml
      sed -i 's/^check_interval = .*/check_interval = {{ runner_interval }}/' /etc/gitlab-runner/config.toml || echo 'check_interval = {{ runner_interval }}' >> /etc/gitlab-runner/config.toml
      sed -i 's/^shutdown_timeout = .*/shutdown_timeout = {{ runner_shutdown_timeout }}/' /etc/gitlab-runner/config.toml || echo 'shutdown_timeout = {{ runner_shutdown_timeout }}' >> /etc/gitlab-runner/config.toml
      sed -i 's/^pull_policy = .*/pull_policy = \"if-not-present\"/' /etc/gitlab-runner/config.toml || echo 'pull_policy = \"if-not-present\"' >> /etc/gitlab-runner/config.toml
      sed -i 's/^shm_size = .*/shm_size = \"256m\"/' /etc/gitlab-runner/config.toml || echo 'shm_size = \"256m\"' >> /etc/gitlab-runner/config.toml
      sed -i 's/^disable_cache = .*/disable_cache = false/' /etc/gitlab-runner/config.toml || echo 'disable_cache = false' >> /etc/gitlab-runner/config.toml
    "
  args:
    executable: /bin/bash
